//@baseURL = http://localhost:4000
@baseURL = https://backend-myidea.herokuapp.com

###
GET {{baseURL}}/status
Content-Type: application/json

###
GET {{baseURL}}/ideas
Content-Type: application/json

###
GET {{baseURL}}/ideas/615ab7ad237c62005a56a665
Content-Type: application/json

###
POST {{baseURL}}/ideas
Content-Type: application/json

{
    "title": "TESTE AO VIVO",
    "description": "TESTE TESTE TESTE",
    "category": "tech",
    "resources": "www.google.com",
    "emails": "guilherme.almeida43@fatec.sp.gov.br",
    "priority": "low"
}

###
PUT {{baseURL}}/ideas
Content-Type: application/json

{
    "_id": "615b82b0d0242c2025abb73b",
    "title": "APP ESCOLA",
    "description": "AAAAAAAAAAAAA",
    "category": "tech",
    "resources": "www.google.com",
    "emails": "guilherme.almeida43@fatec.sp.gov.br",
    "priority": "high"
}

###
DELETE {{baseURL}}/ideas/615b82b0d0242c2025abb73b
Content-Type: application/json
